Add Issues and PR templates
fatih-yavuz/links.dev pull request #175
Opened 2023-01-02 17:16 UTC by esau-morais

## Description 

What types of changes does your code introduce to links.dev?
> :information_source: _Put a `x` in one or more boxes that might apply to it_

- [ ] Sign up (register to `links.dev`)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation (if none of the other choices apply)

## Checklist

> :information_source: _This is simply a reminder of what we are going to look for before merging your code._
> 
>  _Mark the boxes with a `x` that are related to the PR._
> If you're unsure about any of them, don't hesitate to ask. 

- [ ] I have read the ["How to sign up" section](https://github.com/fatih-yavuz/links.dev#how-to-sign-up)
- [x] CI still works with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2023-01-02 20:00 UTC, fatih-yavuz commented
This looks, sweet Esau 

Can we introduce different templates per branch type? For example, the fix or feature branches can be named like `issue-${number}` so that we will ask some of the questions only on those branches:
- CI still works with my changes 
- I have added tests that prove my fix is effective or that my feature works
-  I have added the necessary documentation (if appropriate)
etc. 

For registration PRs, I would only ask the following:
- I have created my-links repository and added my page.json
- my page.json contains my links, not others
- I've updated registry.yaml

2023-01-02 20:22 UTC, esau-morais commented
> This looks, sweet Esau
> 
> Can we introduce different templates per branch type? For example, the fix or feature branches can be named like `issue-${number}` so that we will ask some of the questions only on those branches:
> 
> * CI still works with my changes
> * I have added tests that prove my fix is effective or that my feature works
> * I have added the necessary documentation (if appropriate)
>   etc.
> 
> For registration PRs, I would only ask the following:
> 
> * I have created my-links repository and added my page.json
> * my page.json contains my links, not others
> * I've updated registry.yaml



> This looks, sweet Esau
> 
> Can we introduce different templates per branch type? For example, the fix or feature branches can be named like `issue-${number}` so that we will ask some of the questions only on those branches:
> 
> * CI still works with my changes
> * I have added tests that prove my fix is effective or that my feature works
> * I have added the necessary documentation (if appropriate)
>   etc.
> 
> For registration PRs, I would only ask the following:
> 
> * I have created my-links repository and added my page.json
> * my page.json contains my links, not others
> * I've updated registry.yaml

I love the idea, I was actually unaware that it was possible to also create separated files for PR templates LOL, once I've never seen any org using it. Thank you

2023-01-02 21:49 UTC, fatih-yavuz approved these changes

2023-01-02 21:49 UTC, fatih-yavuz commented on .github/PULL_REQUEST_TEMPLATE/issues.md
> +- [ ] CI still works with my changes
The CI status already indicates that. I think it is unnecessary. What do you think? Other than that, it looks lovely. Thanks for enhancing the README as well 🚀

2023-01-02 22:20 UTC, esau-morais commented on .github/PULL_REQUEST_TEMPLATE/issues.md
> +- [ ] CI still works with my changes
Yes, I agree

2023-01-03 16:25 UTC, esau-morais reviewed
I'd love to also have feedback from @bsoyka and @haliliceylan to proceed with this PR 😄

2023-01-04 10:47 UTC, haliliceylan requested changes
LGTM

2023-01-04 10:47 UTC, haliliceylan commented on README.md
>    2. [Optional] custom.css, which allows you to customize the look of your page.
custom.css => `custom.css`

2023-01-04 12:27 UTC, esau-morais commented on README.md
>    2. [Optional] custom.css, which allows you to customize the look of your page.
Applying changes in the next commit.

2023-01-05 19:00 UTC, merged